// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fabric8-starter": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/fabric8-services/fabric8-starter/design
// --out=$(GOPATH)/src/github.com/fabric8-services/fabric8-starter
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// LabelHref returns the resource href.
func LabelHref(labelID interface{}) string {
	paramlabelID := strings.TrimLeftFunc(fmt.Sprintf("%v", labelID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/labels/%v", paramlabelID)
}

// StatusHref returns the resource href.
func StatusHref() string {
	return "/api/status"
}
